Change examples structure
asyncapi/asyncapi pull request #436
Opened 2020-09-04 22:24 UTC by BlockLucas

Now examples facet for Message & Message Trait objects are an array of any
Fixes #410

2020-09-07 08:28 UTC, fmvilas requested changes
Left some minor tweaks to convey with spec language. Thanks a lot, @BlockLucas!

2020-09-07 08:28 UTC, fmvilas commented on versions/2.0.0/asyncapi.md
> +<a name="messageObjectExamples"></a>examples | [`any`] | An array with examples of valid message objects. Whatever "any" is, it has to match the type defined on payload.
```suggestion
<a name="messageObjectExamples"></a>examples | [`any`] | An array with examples of valid message objects. Whatever "any" is, it MUST match the type defined on the payload. 
```

2020-09-07 08:28 UTC, fmvilas commented on versions/2.0.0/asyncapi.md
> +<a name="messageTraitObjectExamples"></a>examples | [`any`] | An array with examples of valid message objects. Whatever "any" is, it has to match the type defined on payload.
```suggestion
<a name="messageTraitObjectExamples"></a>examples | [`any`] | An array with examples of valid message objects. Whatever "any" is, it MUST match the type defined on the payload. 
```

2020-09-07 17:35 UTC, BlockLucas commented
Thanks, @fmvilas!
Suggestions applied

2020-09-09 09:41 UTC, fmvilas commented
Awesome! Thanks, @BlockLucas!

2020-09-09 09:42 UTC, merged